// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(modelsFFI)
import modelsFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_models_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_models_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureModelsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct Album {
    public var id: Int64
    public var name: String
    public var itemCount: UInt32
    public var coverCacheKey: String?
    public var space: Space

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, name: String, itemCount: UInt32, coverCacheKey: String?, space: Space) {
        self.id = id
        self.name = name
        self.itemCount = itemCount
        self.coverCacheKey = coverCacheKey
        self.space = space
    }
}

#if compiler(>=6)
extension Album: Sendable {}
#endif


extension Album: Equatable, Hashable {
    public static func ==(lhs: Album, rhs: Album) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.itemCount != rhs.itemCount {
            return false
        }
        if lhs.coverCacheKey != rhs.coverCacheKey {
            return false
        }
        if lhs.space != rhs.space {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(itemCount)
        hasher.combine(coverCacheKey)
        hasher.combine(space)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAlbum: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Album {
        return
            try Album(
                id: FfiConverterInt64.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                itemCount: FfiConverterUInt32.read(from: &buf), 
                coverCacheKey: FfiConverterOptionString.read(from: &buf), 
                space: FfiConverterTypeSpace.read(from: &buf)
        )
    }

    public static func write(_ value: Album, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt32.write(value.itemCount, into: &buf)
        FfiConverterOptionString.write(value.coverCacheKey, into: &buf)
        FfiConverterTypeSpace.write(value.space, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlbum_lift(_ buf: RustBuffer) throws -> Album {
    return try FfiConverterTypeAlbum.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlbum_lower(_ value: Album) -> RustBuffer {
    return FfiConverterTypeAlbum.lower(value)
}


public struct ApiCapability {
    public var name: String
    public var path: String
    public var minVersion: UInt32
    public var maxVersion: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, path: String, minVersion: UInt32, maxVersion: UInt32) {
        self.name = name
        self.path = path
        self.minVersion = minVersion
        self.maxVersion = maxVersion
    }
}

#if compiler(>=6)
extension ApiCapability: Sendable {}
#endif


extension ApiCapability: Equatable, Hashable {
    public static func ==(lhs: ApiCapability, rhs: ApiCapability) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        if lhs.minVersion != rhs.minVersion {
            return false
        }
        if lhs.maxVersion != rhs.maxVersion {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(path)
        hasher.combine(minVersion)
        hasher.combine(maxVersion)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeApiCapability: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ApiCapability {
        return
            try ApiCapability(
                name: FfiConverterString.read(from: &buf), 
                path: FfiConverterString.read(from: &buf), 
                minVersion: FfiConverterUInt32.read(from: &buf), 
                maxVersion: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ApiCapability, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterUInt32.write(value.minVersion, into: &buf)
        FfiConverterUInt32.write(value.maxVersion, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApiCapability_lift(_ buf: RustBuffer) throws -> ApiCapability {
    return try FfiConverterTypeApiCapability.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApiCapability_lower(_ value: ApiCapability) -> RustBuffer {
    return FfiConverterTypeApiCapability.lower(value)
}


public struct Asset {
    public var id: Int64
    public var cacheKey: String
    public var filename: String
    public var mediaKind: MediaKind
    public var takenAt: Int64?
    public var addedAt: Int64?
    public var width: UInt32?
    public var height: UInt32?
    public var fileSize: UInt64?
    public var space: Space
    public var serverVersion: Int64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, cacheKey: String, filename: String, mediaKind: MediaKind, takenAt: Int64?, addedAt: Int64?, width: UInt32?, height: UInt32?, fileSize: UInt64?, space: Space, serverVersion: Int64?) {
        self.id = id
        self.cacheKey = cacheKey
        self.filename = filename
        self.mediaKind = mediaKind
        self.takenAt = takenAt
        self.addedAt = addedAt
        self.width = width
        self.height = height
        self.fileSize = fileSize
        self.space = space
        self.serverVersion = serverVersion
    }
}

#if compiler(>=6)
extension Asset: Sendable {}
#endif


extension Asset: Equatable, Hashable {
    public static func ==(lhs: Asset, rhs: Asset) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.cacheKey != rhs.cacheKey {
            return false
        }
        if lhs.filename != rhs.filename {
            return false
        }
        if lhs.mediaKind != rhs.mediaKind {
            return false
        }
        if lhs.takenAt != rhs.takenAt {
            return false
        }
        if lhs.addedAt != rhs.addedAt {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.fileSize != rhs.fileSize {
            return false
        }
        if lhs.space != rhs.space {
            return false
        }
        if lhs.serverVersion != rhs.serverVersion {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(cacheKey)
        hasher.combine(filename)
        hasher.combine(mediaKind)
        hasher.combine(takenAt)
        hasher.combine(addedAt)
        hasher.combine(width)
        hasher.combine(height)
        hasher.combine(fileSize)
        hasher.combine(space)
        hasher.combine(serverVersion)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAsset: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Asset {
        return
            try Asset(
                id: FfiConverterInt64.read(from: &buf), 
                cacheKey: FfiConverterString.read(from: &buf), 
                filename: FfiConverterString.read(from: &buf), 
                mediaKind: FfiConverterTypeMediaKind.read(from: &buf), 
                takenAt: FfiConverterOptionInt64.read(from: &buf), 
                addedAt: FfiConverterOptionInt64.read(from: &buf), 
                width: FfiConverterOptionUInt32.read(from: &buf), 
                height: FfiConverterOptionUInt32.read(from: &buf), 
                fileSize: FfiConverterOptionUInt64.read(from: &buf), 
                space: FfiConverterTypeSpace.read(from: &buf), 
                serverVersion: FfiConverterOptionInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Asset, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.cacheKey, into: &buf)
        FfiConverterString.write(value.filename, into: &buf)
        FfiConverterTypeMediaKind.write(value.mediaKind, into: &buf)
        FfiConverterOptionInt64.write(value.takenAt, into: &buf)
        FfiConverterOptionInt64.write(value.addedAt, into: &buf)
        FfiConverterOptionUInt32.write(value.width, into: &buf)
        FfiConverterOptionUInt32.write(value.height, into: &buf)
        FfiConverterOptionUInt64.write(value.fileSize, into: &buf)
        FfiConverterTypeSpace.write(value.space, into: &buf)
        FfiConverterOptionInt64.write(value.serverVersion, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsset_lift(_ buf: RustBuffer) throws -> Asset {
    return try FfiConverterTypeAsset.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsset_lower(_ value: Asset) -> RustBuffer {
    return FfiConverterTypeAsset.lower(value)
}


public struct Connection {
    public var host: String
    public var verifyTls: Bool
    public var pinnedCertDer: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(host: String, verifyTls: Bool, pinnedCertDer: Data?) {
        self.host = host
        self.verifyTls = verifyTls
        self.pinnedCertDer = pinnedCertDer
    }
}

#if compiler(>=6)
extension Connection: Sendable {}
#endif


extension Connection: Equatable, Hashable {
    public static func ==(lhs: Connection, rhs: Connection) -> Bool {
        if lhs.host != rhs.host {
            return false
        }
        if lhs.verifyTls != rhs.verifyTls {
            return false
        }
        if lhs.pinnedCertDer != rhs.pinnedCertDer {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(host)
        hasher.combine(verifyTls)
        hasher.combine(pinnedCertDer)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnection: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Connection {
        return
            try Connection(
                host: FfiConverterString.read(from: &buf), 
                verifyTls: FfiConverterBool.read(from: &buf), 
                pinnedCertDer: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: Connection, into buf: inout [UInt8]) {
        FfiConverterString.write(value.host, into: &buf)
        FfiConverterBool.write(value.verifyTls, into: &buf)
        FfiConverterOptionData.write(value.pinnedCertDer, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnection_lift(_ buf: RustBuffer) throws -> Connection {
    return try FfiConverterTypeConnection.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnection_lower(_ value: Connection) -> RustBuffer {
    return FfiConverterTypeConnection.lower(value)
}


public struct CrawlProgress {
    public var space: Space
    public var done: UInt64
    public var total: UInt64
    public var complete: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(space: Space, done: UInt64, total: UInt64, complete: Bool) {
        self.space = space
        self.done = done
        self.total = total
        self.complete = complete
    }
}

#if compiler(>=6)
extension CrawlProgress: Sendable {}
#endif


extension CrawlProgress: Equatable, Hashable {
    public static func ==(lhs: CrawlProgress, rhs: CrawlProgress) -> Bool {
        if lhs.space != rhs.space {
            return false
        }
        if lhs.done != rhs.done {
            return false
        }
        if lhs.total != rhs.total {
            return false
        }
        if lhs.complete != rhs.complete {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(space)
        hasher.combine(done)
        hasher.combine(total)
        hasher.combine(complete)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCrawlProgress: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CrawlProgress {
        return
            try CrawlProgress(
                space: FfiConverterTypeSpace.read(from: &buf), 
                done: FfiConverterUInt64.read(from: &buf), 
                total: FfiConverterUInt64.read(from: &buf), 
                complete: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: CrawlProgress, into buf: inout [UInt8]) {
        FfiConverterTypeSpace.write(value.space, into: &buf)
        FfiConverterUInt64.write(value.done, into: &buf)
        FfiConverterUInt64.write(value.total, into: &buf)
        FfiConverterBool.write(value.complete, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrawlProgress_lift(_ buf: RustBuffer) throws -> CrawlProgress {
    return try FfiConverterTypeCrawlProgress.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrawlProgress_lower(_ value: CrawlProgress) -> RustBuffer {
    return FfiConverterTypeCrawlProgress.lower(value)
}


public struct Session {
    public var sid: String
    public var synoToken: String?
    public var username: String
    public var deviceDid: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sid: String, synoToken: String?, username: String, deviceDid: String?) {
        self.sid = sid
        self.synoToken = synoToken
        self.username = username
        self.deviceDid = deviceDid
    }
}

#if compiler(>=6)
extension Session: Sendable {}
#endif


extension Session: Equatable, Hashable {
    public static func ==(lhs: Session, rhs: Session) -> Bool {
        if lhs.sid != rhs.sid {
            return false
        }
        if lhs.synoToken != rhs.synoToken {
            return false
        }
        if lhs.username != rhs.username {
            return false
        }
        if lhs.deviceDid != rhs.deviceDid {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sid)
        hasher.combine(synoToken)
        hasher.combine(username)
        hasher.combine(deviceDid)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSession: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Session {
        return
            try Session(
                sid: FfiConverterString.read(from: &buf), 
                synoToken: FfiConverterOptionString.read(from: &buf), 
                username: FfiConverterString.read(from: &buf), 
                deviceDid: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Session, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sid, into: &buf)
        FfiConverterOptionString.write(value.synoToken, into: &buf)
        FfiConverterString.write(value.username, into: &buf)
        FfiConverterOptionString.write(value.deviceDid, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSession_lift(_ buf: RustBuffer) throws -> Session {
    return try FfiConverterTypeSession.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSession_lower(_ value: Session) -> RustBuffer {
    return FfiConverterTypeSession.lower(value)
}


public struct ThumbnailData {
    public var cachedPath: String
    public var bytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(cachedPath: String, bytes: Data) {
        self.cachedPath = cachedPath
        self.bytes = bytes
    }
}

#if compiler(>=6)
extension ThumbnailData: Sendable {}
#endif


extension ThumbnailData: Equatable, Hashable {
    public static func ==(lhs: ThumbnailData, rhs: ThumbnailData) -> Bool {
        if lhs.cachedPath != rhs.cachedPath {
            return false
        }
        if lhs.bytes != rhs.bytes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(cachedPath)
        hasher.combine(bytes)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeThumbnailData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ThumbnailData {
        return
            try ThumbnailData(
                cachedPath: FfiConverterString.read(from: &buf), 
                bytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ThumbnailData, into buf: inout [UInt8]) {
        FfiConverterString.write(value.cachedPath, into: &buf)
        FfiConverterData.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThumbnailData_lift(_ buf: RustBuffer) throws -> ThumbnailData {
    return try FfiConverterTypeThumbnailData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThumbnailData_lower(_ value: ThumbnailData) -> RustBuffer {
    return FfiConverterTypeThumbnailData.lower(value)
}


public enum CoreError: Swift.Error {

    
    
    case Auth(message: String
    )
    case OtpRequired
    case Network(message: String
    )
    case Decode(message: String
    )
    case UnexpectedResponse(message: String
    )
    case WriteRefused
    case Storage(message: String
    )
    case CapabilityUnavailable(api: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Auth(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .OtpRequired
        case 3: return .Network(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Decode(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .UnexpectedResponse(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .WriteRefused
        case 7: return .Storage(
            message: try FfiConverterString.read(from: &buf)
            )
        case 8: return .CapabilityUnavailable(
            api: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Auth(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case .OtpRequired:
            writeInt(&buf, Int32(2))
        
        
        case let .Network(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Decode(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .UnexpectedResponse(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case .WriteRefused:
            writeInt(&buf, Int32(6))
        
        
        case let .Storage(message):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .CapabilityUnavailable(api):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(api, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lift(_ buf: RustBuffer) throws -> CoreError {
    return try FfiConverterTypeCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lower(_ value: CoreError) -> RustBuffer {
    return FfiConverterTypeCoreError.lower(value)
}


extension CoreError: Equatable, Hashable {}




extension CoreError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MediaKind {
    
    case photo
    case video
    case unknown
}


#if compiler(>=6)
extension MediaKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMediaKind: FfiConverterRustBuffer {
    typealias SwiftType = MediaKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MediaKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .photo
        
        case 2: return .video
        
        case 3: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MediaKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .photo:
            writeInt(&buf, Int32(1))
        
        
        case .video:
            writeInt(&buf, Int32(2))
        
        
        case .unknown:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaKind_lift(_ buf: RustBuffer) throws -> MediaKind {
    return try FfiConverterTypeMediaKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaKind_lower(_ value: MediaKind) -> RustBuffer {
    return FfiConverterTypeMediaKind.lower(value)
}


extension MediaKind: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SessionState {
    
    case valid
    case expired
    case invalid
}


#if compiler(>=6)
extension SessionState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionState: FfiConverterRustBuffer {
    typealias SwiftType = SessionState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .valid
        
        case 2: return .expired
        
        case 3: return .invalid
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SessionState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .valid:
            writeInt(&buf, Int32(1))
        
        
        case .expired:
            writeInt(&buf, Int32(2))
        
        
        case .invalid:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionState_lift(_ buf: RustBuffer) throws -> SessionState {
    return try FfiConverterTypeSessionState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionState_lower(_ value: SessionState) -> RustBuffer {
    return FfiConverterTypeSessionState.lower(value)
}


extension SessionState: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Space {
    
    case personal
    case shared
}


#if compiler(>=6)
extension Space: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpace: FfiConverterRustBuffer {
    typealias SwiftType = Space

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Space {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .personal
        
        case 2: return .shared
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Space, into buf: inout [UInt8]) {
        switch value {
        
        
        case .personal:
            writeInt(&buf, Int32(1))
        
        
        case .shared:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpace_lift(_ buf: RustBuffer) throws -> Space {
    return try FfiConverterTypeSpace.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpace_lower(_ value: Space) -> RustBuffer {
    return FfiConverterTypeSpace.lower(value)
}


extension Space: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ThumbnailSize {
    
    case sm
    case m
    case xl
}


#if compiler(>=6)
extension ThumbnailSize: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeThumbnailSize: FfiConverterRustBuffer {
    typealias SwiftType = ThumbnailSize

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ThumbnailSize {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .sm
        
        case 2: return .m
        
        case 3: return .xl
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ThumbnailSize, into buf: inout [UInt8]) {
        switch value {
        
        
        case .sm:
            writeInt(&buf, Int32(1))
        
        
        case .m:
            writeInt(&buf, Int32(2))
        
        
        case .xl:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThumbnailSize_lift(_ buf: RustBuffer) throws -> ThumbnailSize {
    return try FfiConverterTypeThumbnailSize.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThumbnailSize_lower(_ value: ThumbnailSize) -> RustBuffer {
    return FfiConverterTypeThumbnailSize.lower(value)
}


extension ThumbnailSize: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_models_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureModelsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all