// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(PhotosCoreFFI)
import PhotosCoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_photoscore_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_photoscore_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePhotoscoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * The single UniFFI-exported facade. Swift holds one instance per app run.
 *
 * `Store` wraps a `rusqlite::Connection`, whose internal statement cache uses
 * a `RefCell` and so is not `Sync`. UniFFI objects are shared across threads
 * as `Arc<Self>`, so `store` is held behind a `Mutex` (like `live`) rather
 * than bare, to satisfy `Send + Sync` and to make the cross-thread access
 * pattern explicit rather than accidental.
 *
 * Because `Store` is not `Sync`, `&Store` is not `Send` either, so a
 * `Crawler`/`DeltaReconciler` borrowing it can never be held across an
 * `.await` inside a future the tokio `async_runtime` binding requires to be
 * `Send` (uniffi's exported async methods must return a `Send` future).
 * `crawl_space`/`reconcile_delta` route around this by taking the `Store`
 * *out* of the mutex by value and moving it onto a dedicated blocking
 * thread (`spawn_blocking`), where the whole crawl - including its
 * internal network awaits - runs synchronously via `Handle::block_on`; the
 * owned `Store` is moved back into the mutex once the blocking task
 * returns, even if the crawl itself panicked partway through (the panic is
 * caught on the blocking thread and turned into an ordinary error, see
 * `run_with_store`), so a single bad crawl can never leave the core
 * permanently unusable. The mutex guard itself is only ever held for the
 * instant of the swap, never across any `.await`.
 */
public protocol PhotosCoreProtocol: AnyObject, Sendable {
    
    /**
     * Local-only asset count for `space`; used by tests and diagnostics.
     */
    func assetCount(space: Space) throws  -> UInt64
    
    /**
     * Reads back the persisted crawl progress for `space` with no network
     * access at all. A plain sync `fn` (per the brief's signature); it
     * takes the `store` std `Mutex` only for the duration of the read, so
     * it can never be the source of contention with a concurrent crawl -
     * it simply waits its turn like any other `Mutex` user.
     */
    func crawlProgress(space: Space) throws  -> CrawlProgress
    
    /**
     * Drives a resumable full crawl of `space` to completion (or until
     * interrupted by an error), reporting `CrawlProgress` to `observer`
     * after every page via `ObserverSink`.
     *
     * Requires a live session: fails closed with `CoreError::Auth` if
     * `login`/`restore_session` has not populated `Live`. `page_source_for`
     * takes the `live` std `Mutex` guard only long enough to clone the
     * transport/sid/version it needs and drops it before returning, well
     * before any `.await` here runs.
     *
     * The crawl itself runs via `run_with_store` (see its doc comment):
     * the `store` mutex is only ever locked for the instant needed to move
     * the `Store` out and back in, never across an `.await`.
     */
    func crawlSpace(space: Space, observer: FfiCrawlObserver) async throws  -> CrawlProgress
    
    /**
     * Downloads the original full-resolution bytes for `unit_id` to a
     * temp file and returns its absolute path. Read-only: never writes
     * anything back to the NAS.
     *
     * `unit_id` MUST be `Asset.unit_id`, not `Asset.id`, for the same
     * reason as `thumbnail` above: the download endpoint keys on unit_id.
     *
     * Same lock discipline as `thumbnail`: `live` is locked only long enough
     * to clone the transport/sid/version triple, then dropped before the
     * network `.await`. The destination filename is a hash of
     * `(unit_id, cache_key)` for the same path-safety reason as `thumbnail`
     * (the NAS-supplied `cache_key` never appears literally in a path), and
     * the bytes are written atomically (temp file, then renamed into place).
     *
     * Fails closed with `CoreError::Auth` if no session is held.
     */
    func downloadOriginal(space: Space, unitId: Int64, cacheKey: String) async throws  -> String
    
    /**
     * Local read of every album in `space`, ordered by name. No network
     * access; same lock discipline as `fetch_assets`/`asset_count`.
     */
    func fetchAlbums(space: Space) throws  -> [Album]
    
    /**
     * Windowed local read of assets in `space`, newest-first, for the grid's
     * scrolling. No network access at all: this is a plain sync `fn` that
     * only ever locks `store` for the duration of the read, so it can never
     * block on (or be blocked by) a concurrent crawl for longer than that
     * crawl needs to swap the `Store` back in.
     */
    func fetchAssets(space: Space, offset: UInt32, limit: UInt32) throws  -> [Asset]
    
    /**
     * Fetches the TLS certificate presented by `host` for trust-on-first-use
     * approval, without ever trusting it for a real request (see
     * `synology_api::fetch_server_cert_der` for exactly what is and is not
     * relaxed during this one-shot probe).
     *
     * This is a standalone, session-free call: it can be made before
     * `login` (indeed, that is the intended flow) to let the UI show the
     * user the server's fingerprint + subject and get their approval before
     * ever sending credentials anywhere. Approving means storing the
     * returned `CertInfo.der` (Keychain or app config) and passing it as
     * `Connection.pinned_cert_der` on the `Connection` used for `login`.
     */
    func fetchCertificate(host: String) async throws  -> CertInfo
    
    /**
     * Log in against `connection` with the given credentials.
     *
     * `otp_code` and `device_token` are forwarded to `synology_api::login`
     * untouched:
     * - `otp_code = None` omits the param entirely, so an account with 2FA
     * enabled answers with `CoreError::OtpRequired` (see
     * `synology_api::auth`), which the Swift UI is expected to catch,
     * prompt for a code, and retry with `otp_code = Some(code)`.
     * - `device_token` should be the value previously returned on
     * `Session.device_did` from an earlier login on this host+account
     * (the caller/UI is responsible for persisting it, e.g. Keychain).
     * Passing it lets a trusted device skip OTP; DSM rejecting a stale
     * token falls back to the same `CoreError::OtpRequired` as no token
     * at all (fail-closed, see `synology_api::auth` doc comment).
     *
     * On success, replaces any previously held `Live` state with a fresh
     * transport/session pair (capability probe deferred to first use, so
     * login itself stays a single round trip). The returned `Session`
     * carries any device token DSM minted/confirmed in `device_did`; the
     * caller is expected to persist it for a future `device_token` login.
     */
    func login(connection: Connection, username: String, password: String, otpCode: String?, deviceToken: String?) async throws  -> Session
    
    /**
     * Probe `SYNO.API.Info` over the live session and cache the discovered
     * capability set into `Live.capabilities` for later version pinning
     * (Tasks 36/37 read it via `pin_version`).
     *
     * Fails closed with `CoreError::Auth` if no session is held rather than
     * panicking: a caller that never logged in gets an error to handle, not
     * a crash.
     *
     * A fresh `Transport` is rebuilt from the stored `Connection` inside the
     * lock, then the lock is dropped before the `.await` so the std `Mutex`
     * guard is never held across an await point.
     */
    func probeCapabilities() async throws  -> [ApiCapability]
    
    /**
     * Runs delta reconciliation (new/changed/deleted) for `space` against
     * the live session. Same auth and lock discipline as `crawl_space`.
     */
    func reconcileDelta(space: Space) async throws  -> CrawlProgress
    
    /**
     * Rebuild `Live` state from a previously stored `Session` (e.g. loaded
     * from the Keychain) without re-running the login handshake.
     *
     * Validates the session with a cheap authed capability probe
     * (`SYNO.API.Info`): a probe failure that maps to `CoreError::Auth` or
     * `CoreError::OtpRequired` means the stored session is no longer
     * accepted by DSM, so this reports `SessionState::Expired` rather than
     * an error the caller has to handle as failure - the UI can react by
     * sending the user back through `login`. Any other probe error (e.g.
     * network failure) is fail-closed and propagated as-is.
     */
    func restoreSession(connection: Connection, session: Session) async throws  -> SessionState
    
    /**
     * Sign out: best-effort server-side logout, then unconditionally drop
     * `Live` and clear the per-account thumbnail cache dir contents.
     *
     * Idempotent by construction: if no session is held, `taken` is `None`,
     * the server logout call is skipped, and clearing an already-empty (or
     * absent) cache dir is a no-op, so calling `sign_out` with nothing to
     * sign out of always succeeds.
     */
    func signOut() async throws 
    
    /**
     * Fetches a thumbnail for `unit_id` at `size`, served from a
     * composite-key on-disk cache whenever possible.
     *
     * `unit_id` MUST be `Asset.unit_id` (from `additional.thumbnail.unit_id`
     * on the browse response), NOT `Asset.id`. The Synology thumbnail
     * endpoint keys on unit_id; sending the browse item id returns an html
     * error page instead of image bytes, which is the root cause of a
     * previous blank-thumbnail bug. Callers (the Swift ThumbnailCache) pass
     * `asset.unitId`.
     *
     * The cache path is `{cache_dir}/thumbs/{hex_digest}.jpg`, where
     * `hex_digest` is a hash of `(space, unit_id, size, cache_key)`. Hashing
     * the composite key rather than interpolating any of its parts (in
     * particular the NAS-supplied `cache_key`) directly into the filename
     * means the filename is always a fixed-length hex string: no path
     * separator, no `..`, no length blowup can ever reach the filesystem,
     * even if `cache_key` were ever malformed or unexpectedly large. A
     * changed `cache_key` still hashes to a different digest, so this keeps
     * the same invalidation property as before: whenever the server-side
     * asset changes and the NAS mints a new cache_key, the new call produces
     * a different path and can never be served a stale file.
     *
     * On a cache hit, this returns entirely from disk with no network
     * access. On a miss, `live` is locked only long enough to clone the
     * transport/sid/version triple it needs; the guard is dropped before the
     * `fetch_thumbnail` `.await`, matching the discipline used by
     * `page_source_for`/`crawl_space` elsewhere in this file. The fetched
     * bytes are written atomically (temp file in the same directory, then
     * renamed into place) so a concurrent reader/writer or a symlink planted
     * at the target path can never observe a partial write or be written
     * through.
     *
     * Fails closed with `CoreError::Auth` if no session is held.
     */
    func thumbnail(space: Space, unitId: Int64, cacheKey: String, size: ThumbnailSize) async throws  -> ThumbnailData
    
}
/**
 * The single UniFFI-exported facade. Swift holds one instance per app run.
 *
 * `Store` wraps a `rusqlite::Connection`, whose internal statement cache uses
 * a `RefCell` and so is not `Sync`. UniFFI objects are shared across threads
 * as `Arc<Self>`, so `store` is held behind a `Mutex` (like `live`) rather
 * than bare, to satisfy `Send + Sync` and to make the cross-thread access
 * pattern explicit rather than accidental.
 *
 * Because `Store` is not `Sync`, `&Store` is not `Send` either, so a
 * `Crawler`/`DeltaReconciler` borrowing it can never be held across an
 * `.await` inside a future the tokio `async_runtime` binding requires to be
 * `Send` (uniffi's exported async methods must return a `Send` future).
 * `crawl_space`/`reconcile_delta` route around this by taking the `Store`
 * *out* of the mutex by value and moving it onto a dedicated blocking
 * thread (`spawn_blocking`), where the whole crawl - including its
 * internal network awaits - runs synchronously via `Handle::block_on`; the
 * owned `Store` is moved back into the mutex once the blocking task
 * returns, even if the crawl itself panicked partway through (the panic is
 * caught on the blocking thread and turned into an ordinary error, see
 * `run_with_store`), so a single bad crawl can never leave the core
 * permanently unusable. The mutex guard itself is only ever held for the
 * instant of the swap, never across any `.await`.
 */
open class PhotosCore: PhotosCoreProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_photoscore_fn_clone_photoscore(self.pointer, $0) }
    }
    /**
     * Construct with a local DB directory. Opens/creates SQLite + runs migrations.
     */
public convenience init(dbDir: String, cacheDir: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_photoscore_fn_constructor_photoscore_new(
        FfiConverterString.lower(dbDir),
        FfiConverterString.lower(cacheDir),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_photoscore_fn_free_photoscore(pointer, $0) }
    }

    

    
    /**
     * Local-only asset count for `space`; used by tests and diagnostics.
     */
open func assetCount(space: Space)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_photoscore_fn_method_photoscore_asset_count(self.uniffiClonePointer(),
        FfiConverterTypeSpace_lower(space),$0
    )
})
}
    
    /**
     * Reads back the persisted crawl progress for `space` with no network
     * access at all. A plain sync `fn` (per the brief's signature); it
     * takes the `store` std `Mutex` only for the duration of the read, so
     * it can never be the source of contention with a concurrent crawl -
     * it simply waits its turn like any other `Mutex` user.
     */
open func crawlProgress(space: Space)throws  -> CrawlProgress  {
    return try  FfiConverterTypeCrawlProgress_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_photoscore_fn_method_photoscore_crawl_progress(self.uniffiClonePointer(),
        FfiConverterTypeSpace_lower(space),$0
    )
})
}
    
    /**
     * Drives a resumable full crawl of `space` to completion (or until
     * interrupted by an error), reporting `CrawlProgress` to `observer`
     * after every page via `ObserverSink`.
     *
     * Requires a live session: fails closed with `CoreError::Auth` if
     * `login`/`restore_session` has not populated `Live`. `page_source_for`
     * takes the `live` std `Mutex` guard only long enough to clone the
     * transport/sid/version it needs and drops it before returning, well
     * before any `.await` here runs.
     *
     * The crawl itself runs via `run_with_store` (see its doc comment):
     * the `store` mutex is only ever locked for the instant needed to move
     * the `Store` out and back in, never across an `.await`.
     */
open func crawlSpace(space: Space, observer: FfiCrawlObserver)async throws  -> CrawlProgress  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photoscore_fn_method_photoscore_crawl_space(
                    self.uniffiClonePointer(),
                    FfiConverterTypeSpace_lower(space),FfiConverterCallbackInterfaceFfiCrawlObserver_lower(observer)
                )
            },
            pollFunc: ffi_photoscore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photoscore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photoscore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeCrawlProgress_lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * Downloads the original full-resolution bytes for `unit_id` to a
     * temp file and returns its absolute path. Read-only: never writes
     * anything back to the NAS.
     *
     * `unit_id` MUST be `Asset.unit_id`, not `Asset.id`, for the same
     * reason as `thumbnail` above: the download endpoint keys on unit_id.
     *
     * Same lock discipline as `thumbnail`: `live` is locked only long enough
     * to clone the transport/sid/version triple, then dropped before the
     * network `.await`. The destination filename is a hash of
     * `(unit_id, cache_key)` for the same path-safety reason as `thumbnail`
     * (the NAS-supplied `cache_key` never appears literally in a path), and
     * the bytes are written atomically (temp file, then renamed into place).
     *
     * Fails closed with `CoreError::Auth` if no session is held.
     */
open func downloadOriginal(space: Space, unitId: Int64, cacheKey: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photoscore_fn_method_photoscore_download_original(
                    self.uniffiClonePointer(),
                    FfiConverterTypeSpace_lower(space),FfiConverterInt64.lower(unitId),FfiConverterString.lower(cacheKey)
                )
            },
            pollFunc: ffi_photoscore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photoscore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photoscore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * Local read of every album in `space`, ordered by name. No network
     * access; same lock discipline as `fetch_assets`/`asset_count`.
     */
open func fetchAlbums(space: Space)throws  -> [Album]  {
    return try  FfiConverterSequenceTypeAlbum.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_photoscore_fn_method_photoscore_fetch_albums(self.uniffiClonePointer(),
        FfiConverterTypeSpace_lower(space),$0
    )
})
}
    
    /**
     * Windowed local read of assets in `space`, newest-first, for the grid's
     * scrolling. No network access at all: this is a plain sync `fn` that
     * only ever locks `store` for the duration of the read, so it can never
     * block on (or be blocked by) a concurrent crawl for longer than that
     * crawl needs to swap the `Store` back in.
     */
open func fetchAssets(space: Space, offset: UInt32, limit: UInt32)throws  -> [Asset]  {
    return try  FfiConverterSequenceTypeAsset.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_photoscore_fn_method_photoscore_fetch_assets(self.uniffiClonePointer(),
        FfiConverterTypeSpace_lower(space),
        FfiConverterUInt32.lower(offset),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
    
    /**
     * Fetches the TLS certificate presented by `host` for trust-on-first-use
     * approval, without ever trusting it for a real request (see
     * `synology_api::fetch_server_cert_der` for exactly what is and is not
     * relaxed during this one-shot probe).
     *
     * This is a standalone, session-free call: it can be made before
     * `login` (indeed, that is the intended flow) to let the UI show the
     * user the server's fingerprint + subject and get their approval before
     * ever sending credentials anywhere. Approving means storing the
     * returned `CertInfo.der` (Keychain or app config) and passing it as
     * `Connection.pinned_cert_der` on the `Connection` used for `login`.
     */
open func fetchCertificate(host: String)async throws  -> CertInfo  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photoscore_fn_method_photoscore_fetch_certificate(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(host)
                )
            },
            pollFunc: ffi_photoscore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photoscore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photoscore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeCertInfo_lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * Log in against `connection` with the given credentials.
     *
     * `otp_code` and `device_token` are forwarded to `synology_api::login`
     * untouched:
     * - `otp_code = None` omits the param entirely, so an account with 2FA
     * enabled answers with `CoreError::OtpRequired` (see
     * `synology_api::auth`), which the Swift UI is expected to catch,
     * prompt for a code, and retry with `otp_code = Some(code)`.
     * - `device_token` should be the value previously returned on
     * `Session.device_did` from an earlier login on this host+account
     * (the caller/UI is responsible for persisting it, e.g. Keychain).
     * Passing it lets a trusted device skip OTP; DSM rejecting a stale
     * token falls back to the same `CoreError::OtpRequired` as no token
     * at all (fail-closed, see `synology_api::auth` doc comment).
     *
     * On success, replaces any previously held `Live` state with a fresh
     * transport/session pair (capability probe deferred to first use, so
     * login itself stays a single round trip). The returned `Session`
     * carries any device token DSM minted/confirmed in `device_did`; the
     * caller is expected to persist it for a future `device_token` login.
     */
open func login(connection: Connection, username: String, password: String, otpCode: String?, deviceToken: String?)async throws  -> Session  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photoscore_fn_method_photoscore_login(
                    self.uniffiClonePointer(),
                    FfiConverterTypeConnection_lower(connection),FfiConverterString.lower(username),FfiConverterString.lower(password),FfiConverterOptionString.lower(otpCode),FfiConverterOptionString.lower(deviceToken)
                )
            },
            pollFunc: ffi_photoscore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photoscore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photoscore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSession_lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * Probe `SYNO.API.Info` over the live session and cache the discovered
     * capability set into `Live.capabilities` for later version pinning
     * (Tasks 36/37 read it via `pin_version`).
     *
     * Fails closed with `CoreError::Auth` if no session is held rather than
     * panicking: a caller that never logged in gets an error to handle, not
     * a crash.
     *
     * A fresh `Transport` is rebuilt from the stored `Connection` inside the
     * lock, then the lock is dropped before the `.await` so the std `Mutex`
     * guard is never held across an await point.
     */
open func probeCapabilities()async throws  -> [ApiCapability]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photoscore_fn_method_photoscore_probe_capabilities(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_photoscore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photoscore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photoscore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeApiCapability.lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * Runs delta reconciliation (new/changed/deleted) for `space` against
     * the live session. Same auth and lock discipline as `crawl_space`.
     */
open func reconcileDelta(space: Space)async throws  -> CrawlProgress  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photoscore_fn_method_photoscore_reconcile_delta(
                    self.uniffiClonePointer(),
                    FfiConverterTypeSpace_lower(space)
                )
            },
            pollFunc: ffi_photoscore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photoscore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photoscore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeCrawlProgress_lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * Rebuild `Live` state from a previously stored `Session` (e.g. loaded
     * from the Keychain) without re-running the login handshake.
     *
     * Validates the session with a cheap authed capability probe
     * (`SYNO.API.Info`): a probe failure that maps to `CoreError::Auth` or
     * `CoreError::OtpRequired` means the stored session is no longer
     * accepted by DSM, so this reports `SessionState::Expired` rather than
     * an error the caller has to handle as failure - the UI can react by
     * sending the user back through `login`. Any other probe error (e.g.
     * network failure) is fail-closed and propagated as-is.
     */
open func restoreSession(connection: Connection, session: Session)async throws  -> SessionState  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photoscore_fn_method_photoscore_restore_session(
                    self.uniffiClonePointer(),
                    FfiConverterTypeConnection_lower(connection),FfiConverterTypeSession_lower(session)
                )
            },
            pollFunc: ffi_photoscore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photoscore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photoscore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSessionState_lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * Sign out: best-effort server-side logout, then unconditionally drop
     * `Live` and clear the per-account thumbnail cache dir contents.
     *
     * Idempotent by construction: if no session is held, `taken` is `None`,
     * the server logout call is skipped, and clearing an already-empty (or
     * absent) cache dir is a no-op, so calling `sign_out` with nothing to
     * sign out of always succeeds.
     */
open func signOut()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photoscore_fn_method_photoscore_sign_out(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_photoscore_rust_future_poll_void,
            completeFunc: ffi_photoscore_rust_future_complete_void,
            freeFunc: ffi_photoscore_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * Fetches a thumbnail for `unit_id` at `size`, served from a
     * composite-key on-disk cache whenever possible.
     *
     * `unit_id` MUST be `Asset.unit_id` (from `additional.thumbnail.unit_id`
     * on the browse response), NOT `Asset.id`. The Synology thumbnail
     * endpoint keys on unit_id; sending the browse item id returns an html
     * error page instead of image bytes, which is the root cause of a
     * previous blank-thumbnail bug. Callers (the Swift ThumbnailCache) pass
     * `asset.unitId`.
     *
     * The cache path is `{cache_dir}/thumbs/{hex_digest}.jpg`, where
     * `hex_digest` is a hash of `(space, unit_id, size, cache_key)`. Hashing
     * the composite key rather than interpolating any of its parts (in
     * particular the NAS-supplied `cache_key`) directly into the filename
     * means the filename is always a fixed-length hex string: no path
     * separator, no `..`, no length blowup can ever reach the filesystem,
     * even if `cache_key` were ever malformed or unexpectedly large. A
     * changed `cache_key` still hashes to a different digest, so this keeps
     * the same invalidation property as before: whenever the server-side
     * asset changes and the NAS mints a new cache_key, the new call produces
     * a different path and can never be served a stale file.
     *
     * On a cache hit, this returns entirely from disk with no network
     * access. On a miss, `live` is locked only long enough to clone the
     * transport/sid/version triple it needs; the guard is dropped before the
     * `fetch_thumbnail` `.await`, matching the discipline used by
     * `page_source_for`/`crawl_space` elsewhere in this file. The fetched
     * bytes are written atomically (temp file in the same directory, then
     * renamed into place) so a concurrent reader/writer or a symlink planted
     * at the target path can never observe a partial write or be written
     * through.
     *
     * Fails closed with `CoreError::Auth` if no session is held.
     */
open func thumbnail(space: Space, unitId: Int64, cacheKey: String, size: ThumbnailSize)async throws  -> ThumbnailData  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photoscore_fn_method_photoscore_thumbnail(
                    self.uniffiClonePointer(),
                    FfiConverterTypeSpace_lower(space),FfiConverterInt64.lower(unitId),FfiConverterString.lower(cacheKey),FfiConverterTypeThumbnailSize_lower(size)
                )
            },
            pollFunc: ffi_photoscore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photoscore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photoscore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeThumbnailData_lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePhotosCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PhotosCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PhotosCore {
        return PhotosCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PhotosCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PhotosCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PhotosCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhotosCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> PhotosCore {
    return try FfiConverterTypePhotosCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhotosCore_lower(_ value: PhotosCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypePhotosCore.lower(value)
}






/**
 * Implemented on the Swift side; called from Rust during crawl_space.
 */
public protocol FfiCrawlObserver: AnyObject, Sendable {
    
    func onProgress(progress: CrawlProgress) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFfiCrawlObserver {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceFfiCrawlObserver] = [UniffiVTableCallbackInterfaceFfiCrawlObserver(
        onProgress: { (
            uniffiHandle: UInt64,
            progress: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiCrawlObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     progress: try FfiConverterTypeCrawlProgress_lift(progress)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceFfiCrawlObserver.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface FfiCrawlObserver: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitFfiCrawlObserver() {
    uniffi_photoscore_fn_init_callback_vtable_fficrawlobserver(UniffiCallbackInterfaceFfiCrawlObserver.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceFfiCrawlObserver {
    fileprivate static let handleMap = UniffiHandleMap<FfiCrawlObserver>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceFfiCrawlObserver : FfiConverter {
    typealias SwiftType = FfiCrawlObserver
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceFfiCrawlObserver_lift(_ handle: UInt64) throws -> FfiCrawlObserver {
    return try FfiConverterCallbackInterfaceFfiCrawlObserver.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceFfiCrawlObserver_lower(_ v: FfiCrawlObserver) -> UInt64 {
    return FfiConverterCallbackInterfaceFfiCrawlObserver.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAlbum: FfiConverterRustBuffer {
    typealias SwiftType = [Album]

    public static func write(_ value: [Album], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAlbum.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Album] {
        let len: Int32 = try readInt(&buf)
        var seq = [Album]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAlbum.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeApiCapability: FfiConverterRustBuffer {
    typealias SwiftType = [ApiCapability]

    public static func write(_ value: [ApiCapability], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeApiCapability.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ApiCapability] {
        let len: Int32 = try readInt(&buf)
        var seq = [ApiCapability]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeApiCapability.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAsset: FfiConverterRustBuffer {
    typealias SwiftType = [Asset]

    public static func write(_ value: [Asset], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAsset.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Asset] {
        let len: Int32 = try readInt(&buf)
        var seq = [Asset]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAsset.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsurePhotoscoreInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * Trivial cross-boundary smoke function. Returns the core crate version.
 * Proves Swift can call into Rust over UniFFI before the full PhotosCore lands.
 */
public func coreVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_photoscore_fn_func_core_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_photoscore_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_photoscore_checksum_func_core_version() != 53489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_asset_count() != 15676) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_crawl_progress() != 63576) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_crawl_space() != 58321) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_download_original() != 35832) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_fetch_albums() != 8838) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_fetch_assets() != 29559) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_fetch_certificate() != 19983) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_login() != 52991) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_probe_capabilities() != 23336) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_reconcile_delta() != 18507) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_restore_session() != 22452) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_sign_out() != 54821) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_photoscore_thumbnail() != 41967) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_constructor_photoscore_new() != 54313) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photoscore_checksum_method_fficrawlobserver_on_progress() != 44887) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitFfiCrawlObserver()
    uniffiEnsureModelsInitialized()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePhotoscoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all